from pysc2.lib import actions


class Unit:
    def __init__(self, name, build_id, train_id, unit_id):
        self.name = name
        self.build_id = build_id
        self.train_id = train_id
        self.unit_id = unit_id


# Unit IDs
PROTOSS_ADEPT = 311
PROTOSS_ADEPTPHASESHIFT = 801
PROTOSS_ARCHON = 141
PROTOSS_ASSIMILATOR = 61
PROTOSS_CARRIER = 79
PROTOSS_COLOSSUS = 4
PROTOSS_CYBERNETICSCORE = 72
PROTOSS_DARKSHRINE = 69
PROTOSS_DARKTEMPLAR = 76
PROTOSS_DISRUPTOR = 694
PROTOSS_DISRUPTORPHASED = 733
PROTOSS_FLEETBEACON = 64
PROTOSS_FORGE = 63
PROTOSS_GATEWAY = 62
PROTOSS_HIGHTEMPLAR = 75
PROTOSS_IMMORTAL = 83
PROTOSS_INTERCEPTOR = 85
PROTOSS_MOTHERSHIP = 10  # ,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_PHOTONOVERCHARGE, EFFECT_TIMEWARP, STOP, ATTACK, EFFECT_MASSRECALL
PROTOSS_MOTHERSHIPCORE = 488  # ,   // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_MOTHERSHIP, EFFECT_PHOTONOVERCHARGE, EFFECT_TIMEWARP, CANCEL, STOP, ATTACK, EFFECT_MASSRECALL
PROTOSS_NEXUS = 59  # ,    // SMART, EFFECT_CHRONOBOOST, TRAIN_PROBE, TRAIN_MOTHERSHIPCORE, CANCEL, CANCEL_LAST, RALLY_WORKERS
PROTOSS_OBSERVER = 82  # ,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, ATTACK
PROTOSS_ORACLE = 495  # ,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_ORACLEREVELATION, BEHAVIOR_PULSARBEAMON, BEHAVIOR_PULSARBEAMOFF, BUILD_STASISTRAP, CANCEL, STOP, ATTACK
PROTOSS_ORACLESTASISTRAP = 732  # ,   // CANCEL
PROTOSS_PHOENIX = 78  # ,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_GRAVITONBEAM, CANCEL, STOP, ATTACK
PROTOSS_PHOTONCANNON = 66  # ,    // SMART, CANCEL, STOP, ATTACK
PROTOSS_PROBE = 84  # ,    // SMART, MOVE, PATROL, HOLDPOSITION, BUILD_NEXUS, BUILD_PYLON, BUILD_ASSIMILATOR, BUILD_GATEWAY, BUILD_FORGE, BUILD_FLEETBEACON, BUILD_TWILIGHTCOUNCIL, BUILD_PHOTONCANNON, BUILD_STARGATE, BUILD_TEMPLARARCHIVE, BUILD_DARKSHRINE, BUILD_ROBOTICSBAY, BUILD_ROBOTICSFACILITY, BUILD_CYBERNETICSCORE, STOP, HARVEST_GATHER, HARVEST_RETURN, ATTACK, EFFECT_SPRAY
PROTOSS_PYLON = 60  # ,    // CANCEL
PROTOSS_PYLONOVERCHARGED = 894  # ,   // SMART, STOP, ATTACK
PROTOSS_ROBOTICSBAY = 70  # ,    // RESEARCH_GRAVITICBOOSTER, RESEARCH_GRAVITICDRIVE, RESEARCH_EXTENDEDTHERMALLANCE, CANCEL, CANCEL_LAST
PROTOSS_ROBOTICSFACILITY = 71  # ,    // SMART, TRAIN_WARPPRISM, TRAIN_OBSERVER, TRAIN_COLOSSUS, TRAIN_IMMORTAL, TRAIN_DISRUPTOR, CANCEL, CANCEL_LAST, RALLY_UNITS
PROTOSS_SENTRY = 77  # ,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_GUARDIANSHIELD, HALLUCINATION_ARCHON, HALLUCINATION_COLOSSUS, HALLUCINATION_HIGHTEMPLAR, HALLUCINATION_IMMORTAL, HALLUCINATION_PHOENIX, HALLUCINATION_PROBE, HALLUCINATION_STALKER, HALLUCINATION_VOIDRAY, HALLUCINATION_WARPPRISM, HALLUCINATION_ZEALOT, EFFECT_FORCEFIELD, HALLUCINATION_ORACLE, HALLUCINATION_DISRUPTOR, HALLUCINATION_ADEPT, STOP, RALLY_UNITS, ATTACK
PROTOSS_STALKER = 74  # ,    // SMART, MOVE, PATROL, HOLDPOSITION, STOP, RALLY_UNITS, ATTACK, EFFECT_BLINK
PROTOSS_STARGATE = 67  # ,    // SMART, TRAIN_PHOENIX, TRAIN_CARRIER, TRAIN_VOIDRAY, TRAIN_ORACLE, TRAIN_TEMPEST, CANCEL, CANCEL_LAST, RALLY_UNITS
PROTOSS_TEMPEST = 496  # ,   // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_TEMPESTDISRUPTIONBLAST, CANCEL, STOP, ATTACK
PROTOSS_TEMPLARARCHIVE = 68  # ,    // RESEARCH_PSISTORM, CANCEL, CANCEL_LAST
PROTOSS_TWILIGHTCOUNCIL = 65  # ,    // RESEARCH_CHARGE, RESEARCH_BLINK, RESEARCH_ADEPTRESONATINGGLAIVES, CANCEL, CANCEL_LAST
PROTOSS_VOIDRAY = 80  # ,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_VOIDRAYPRISMATICALIGNMENT, STOP, ATTACK
PROTOSS_WARPGATE = 133  # // SMART, TRAINWARP_ZEALOT, TRAINWARP_STALKER, TRAINWARP_HIGHTEMPLAR, TRAINWARP_DARKTEMPLAR, TRAINWARP_SENTRY, TRAINWARP_ADEPT, MORPH_GATEWAY
PROTOSS_WARPPRISM = 81  # ,    // SMART, MOVE, PATROL, HOLDPOSITION, MORPH_WARPPRISMPHASINGMODE, STOP, LOAD, UNLOADALLAT, ATTACK
PROTOSS_WARPPRISMPHASING = 136  # ,   // SMART, MORPH_WARPPRISMTRANSPORTMODE, STOP, LOAD, UNLOADALLAT
PROTOSS_ZEALOT = 73  # ,    // SMART, MOVE, PATROL, HOLDPOSITION, EFFECT_CHARGE, STOP, RALLY_UNITS, ATTACK  # Train IDs

# train actions
_TRAIN_ZEALOT = actions.FUNCTIONS.Train_Zealot_quick.id
_TRAIN_STALKER = actions.FUNCTIONS.Train_Stalker_quick.id
_TRAIN_SENTRY = actions.FUNCTIONS.Train_Sentry_quick.id
_TRAIN_HIGHTEMPLAR = actions.FUNCTIONS.Train_HighTemplar_quick.id
_TRAIN_DARKTEMPLAR = actions.FUNCTIONS.Train_DarkTemplar_quick.id
_TRAIN_ADEPT = actions.FUNCTIONS.Train_Adept_quick.id

_TRAIN_OBSERVER = actions.FUNCTIONS.Train_Observer_quick.id
_TRAIN_IMMORTAL = actions.FUNCTIONS.Train_Immortal_quick.id
_TRAIN_WARPPRISM = actions.FUNCTIONS.Train_WarpPrism_quick.id
_TRAIN_COLOSSUS = actions.FUNCTIONS.Train_Colossus_quick.id
_TRAIN_DISRUPTOR = actions.FUNCTIONS.Train_Disruptor_quick.id

_TRAIN_PHOENIX = actions.FUNCTIONS.Train_Phoenix_quick.id
_TRAIN_VOIDRAY = actions.FUNCTIONS.Train_VoidRay_quick.id
_TRAIN_CARRIER = actions.FUNCTIONS.Train_Carrier_quick.id
_TRAIN_ORACLE = actions.FUNCTIONS.Train_Oracle_quick.id
_TRAIN_TEMPEST = actions.FUNCTIONS.Train_Tempest_quick.id


Zealot = Unit('zealot', build_id=PROTOSS_GATEWAY, train_id=_TRAIN_ZEALOT, unit_id=PROTOSS_ZEALOT)
Stalker = Unit('stalker', build_id=PROTOSS_GATEWAY, train_id=_TRAIN_STALKER, unit_id=PROTOSS_STALKER)
Sentry = Unit('sentry', build_id=PROTOSS_GATEWAY, train_id=_TRAIN_SENTRY, unit_id=PROTOSS_SENTRY)
HighTemplar = Unit('highTemplar', build_id=PROTOSS_GATEWAY, train_id=_TRAIN_HIGHTEMPLAR, unit_id=PROTOSS_HIGHTEMPLAR)
Dark = Unit('darkTemplar', build_id=PROTOSS_GATEWAY, train_id=_TRAIN_DARKTEMPLAR, unit_id=PROTOSS_DARKTEMPLAR)
Adept = Unit('adept', build_id=PROTOSS_GATEWAY, train_id=_TRAIN_ADEPT, unit_id=PROTOSS_ADEPT)

Observer = Unit('observer', build_id=PROTOSS_ROBOTICSFACILITY, train_id=_TRAIN_OBSERVER, unit_id=PROTOSS_OBSERVER)
Immortal = Unit('immortal', build_id=PROTOSS_ROBOTICSFACILITY, train_id=_TRAIN_IMMORTAL, unit_id=PROTOSS_IMMORTAL)
WarpPrism = Unit('warpPrism', build_id=PROTOSS_ROBOTICSFACILITY, train_id=_TRAIN_WARPPRISM, unit_id=PROTOSS_WARPPRISM)
Colossus = Unit('colossus', build_id=PROTOSS_ROBOTICSFACILITY, train_id=_TRAIN_COLOSSUS, unit_id=PROTOSS_COLOSSUS)
Disruptor = Unit('disruptor', build_id=PROTOSS_ROBOTICSFACILITY, train_id=_TRAIN_DISRUPTOR, unit_id=PROTOSS_DISRUPTOR)

Phoenix = Unit('phoenix', build_id=PROTOSS_STARGATE, train_id=_TRAIN_PHOENIX, unit_id=PROTOSS_PHOENIX)
VoidRay = Unit('voidRay', build_id=PROTOSS_STARGATE, train_id=_TRAIN_VOIDRAY, unit_id=PROTOSS_VOIDRAY)
Carrier = Unit('carrier', build_id=PROTOSS_STARGATE, train_id=_TRAIN_CARRIER, unit_id=PROTOSS_CARRIER)
Oracle = Unit('carrier', build_id=PROTOSS_STARGATE, train_id=_TRAIN_ORACLE, unit_id=PROTOSS_ORACLE)
Tempest = Unit('tempest', build_id=PROTOSS_STARGATE, train_id=_TRAIN_TEMPEST, unit_id=PROTOSS_TEMPEST)





